version: '3.8'

# 定义网络，让所有容器在同一个内网里互相通信
networks:
  monitor_net:
    driver: bridge

# 定义数据卷，保证数据库和中间件重启后数据不丢失（极其重要的企业级规范！）
volumes:
  mysql_data:
  redis_data:

services:
  # ================= 1. 核心数据库 =================
  mysql-db:
    image: mysql:8.0
    container_name: monitor-mysql
    restart: always
    environment:
      # 这里配置的密码，后端 application-prod.yml 会自动读取
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: monitor_system
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql # 这个文件会在容器第一次启动时自动执行，创建表结构和初始数据
    networks:
      - monitor_net

  # ================= 2. 向量数据库 (RAG 持久化大脑) =================
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: monitor-redis-stack
    restart: always
    environment:
      # 设置 Redis 密码
      REDIS_ARGS: "--requirepass 123456"
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitor_net

  # ================= 3. 消息队列 (硬件高并发缓冲) =================
  rabbitmq:
    # 使用带 management 的版本，自带一个精美的浏览器监控后台
    image: rabbitmq:3-management
    container_name: monitor-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      TZ: Asia/Shanghai
    ports:
      - "5672:5672"   # 代码通信端口
      - "15672:15672" # 浏览器后台管理端口
    networks:
      - monitor_net

  # ================= 4. Java 核心后端 =================
  monitor-backend:
    build: 
      context: ./monitor-system  # 指向你的后端代码目录，它会去寻找 Dockerfile
    container_name: monitor-backend
    restart: always
    depends_on:
      - mysql-db
      - redis-stack
      - rabbitmq
    environment:
      # 切换到生产环境配置
      - SPRING_PROFILES_ACTIVE=prod
      # 注入环境依赖的宿主机名（指向上面定义的容器）
      - DB_HOST=mysql-db
      - DB_PASSWORD=123456
      - REDIS_HOST=redis-stack
      - REDIS_PASSWORD=123456
      - MQ_HOST=rabbitmq
      - MQ_PASSWORD=123456
      - ZHIPU_API_KEY=${ZHIPU_API_KEY} # 智谱 AI Key，让 Docker 从宿主机的 .env 文件中读取并传给容器
      - TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    networks:
      - monitor_net

  # ================= 5. Vue 监控大屏前端 =================
  monitor-frontend:
    build: 
      context: ./monitor-system-ui # 指向你的前端代码目录
    container_name: monitor-frontend
    restart: always
    depends_on:
      - monitor-backend
    ports:
      - "80:80" # 前端直接暴露在 80 端口，浏览器不用输端口号直接访问
    networks:
      - monitor_net