server {
    listen       80;
    server_name  localhost;

    # 1. 处理前端静态文件与 Vue 路由历史模式
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 核心：如果找不到文件，就统统重定向给 index.html，解决刷新 404 问题
        try_files $uri $uri/ /index.html; 
    }

    # 2. 解决跨域与反向代理：把带有 /api 的请求，偷偷转发给后端容器
    location /api/ {
        # 注意：这里的 monitor-backend 必须和你 docker-compose.yml 里写的后端服务名一模一样！
        proxy_pass http://monitor-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}